server:
  port: 8091

spring:
  application:
    name: small-square-microservice

  datasource:
    url: jdbc:mysql://localhost:3306/small_square_microservice
    username: root
    password:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka
